### ISSUE TITLE
Ertekeles

### ISSUE THREAD

**Issue by hegyhati** [Teaching-projects/SZE-FordProg-Yoda#1]

**Comment by hegyhati** [comment]
@AdamHorv @AdamHorva 
No, meglestem, szoval en kicsit kaotikusnak latom a dolgot. De az is latszik, hogy jo sok munkat beletettel. En most egy harmas fele hajlok.

**Comment by AdamHorva** [comment]
Én ezzel megelégszem. Köszönöm.

**Comment by hegyhati** [comment]
Be is irtam, midnen jot, jo nyarat!
